import Head from "next/head";
import { Inter } from "next/font/google";
import { useState } from "react";
import Timer from "@/components/timer";

const inter = Inter({ subsets: ["latin"] });

export default function Counter() {
  const [pre, setPre] = useState("");
  const [state, setState] = useState("running");
  const [time, setTime] = useState(71726);

  const klik = async () => {
    const api = "/api/hello";
    const url = "https://dbs.arms.workers.dev/countries/ps/rand/10";
    const rs = await fetch(url);
    if (rs.ok) {
      const json = await rs.json();
      setPre(JSON.stringify(json.data[0], null, 2));
    }
  };

  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container px-4">
        <h1 className="text-3xl font-medium mt-3 mb-2">Hello world!</h1>
        <button onClick={klik} className="bg-gray-200 active:bg-gray-300 px-6 py-2">
          API GET
        </button>
        <span>{Math.ceil(time / 1000)}</span>
        <Timer duration={time} counter={setTime} state={state} />
        <pre id="pre" className="text-xs my-4">
          {pre || "PLACEHOLDER"}
        </pre>
      </main>
    </>
  );
}
